---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  app.kubernetes.io/component: app
  app.kubernetes.io/instance: "medis-rls-dc"
  app.kubernetes.io/managed-by: kubectl
  app.kubernetes.io/name: nodejs
  app.kubernetes.io/part-of: "medis-rls-dc"
  app: "medis-rls-dc"
  template: "medis-rls-dc-template"
metadata:
  name: "medis-rls-dc"
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "allow-${APP_NAME}-app-${JOB_NAME}-to-rls-patroni-${ENVIRONMENT_NAME}-cluster"
    spec:
      # Allow app to talk to Patroni cluster
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: "${APP_NAME}.${JOB_NAME}"
                  role: app
          ports:
            - port: 5432
              protocol: TCP
      podSelector:
        matchLabels:
          cluster-name: "rls-patroni-${ENVIRONMENT_NAME}"
          role: master
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: "allow-${APP_NAME}-pre-hook-to-rls-patroni-${ENVIRONMENT_NAME}-cluster"
    spec:
      # Allow app pre-hook pods to talk to Patroni cluster
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-pre
          ports:
            - port: 5432
              protocol: TCP
      podSelector:
        matchLabels:
          cluster-name: "rls-patroni-${ENVIRONMENT_NAME}"
          role: master
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: "${APP_NAME}-app-${JOB_NAME}"
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: "${APP_NAME}.${JOB_NAME}"
        role: app
      strategy:
        type: RollingUpdate
        resources: {}
        rollingParams:
          timeoutSeconds: 600
          pre:
            failurePolicy: Retry
            execNewPod:
              command:
                - npm
                - run
                - migrate
              containerName: "app"
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_HOST
                  value: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: SERVER_BASEPATH
                  value: "${ROUTE_PATH}"
      template:
        metadata:
          labels:
            app: "${APP_NAME}.${JOB_NAME}"
            role: app
        spec:
          containers:
            - name: app
              image: "${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${APP_NAME}:${JOB_NAME}"
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: "${ROUTE_PATH}/api"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 3
                failureThreshold: 3
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: "${ROUTE_PATH}/api"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 3
                failureThreshold: 1
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_HOST
                  value: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: "rls-patroni-${ENVIRONMENT_NAME}"
                - name: FRONTEND_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: VITE_FRONTEND_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: VITE_CONTACT
                  valueFrom:
                    secretKeyRef:
                      key: email
                      name: "${APP_NAME}-contact-secret"

                - name: VITE_HOWTOURL
                  valueFrom:
                    secretKeyRef:
                      key: howtovideourl
                      name: "${APP_NAME}-landingpagevideourls-secret"
                - name: VITE_CHEFSTOURURL
                  valueFrom:
                    secretKeyRef:
                      key: chefstourvideourl
                      name: "${APP_NAME}-landingpagevideourls-secret"
                - name: VITE_CHEFS_GEO_ADDRESS_APIURL
                  valueFrom:
                    secretKeyRef:
                      key: chefsgeoaddressapiurl
                      name: "${APP_NAME}-bcgeoaddress-secret"
                - name: VITE_CHEFS_ADVANCE_GEO_ADDRESS_APIURL
                  valueFrom:
                    secretKeyRef:
                      key: chefsadvancegeoaddressapiurl
                      name: "${APP_NAME}-bcgeoaddress-secret"
                - name: VITE_BC_GEO_ADDRESS_APIURL
                  valueFrom:
                    secretKeyRef:
                      key: bcgeoaddressapiurl
                      name: "${APP_NAME}-bcgeoaddress-secret"
                - name: SERVER_BASEPATH
                  value: "${ROUTE_PATH}"
                - name: SC_CS_CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: ches_client_id
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: ches_client_secret
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CDOGS_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: cdogs_client_id
                      name: "${APP_NAME}-sc-cs-secret"
                - name: SC_CS_CDOGS_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: cdogs_client_secret
                      name: "${APP_NAME}-sc-cs-secret"
                - name: FILES_OBJECTSTORAGE_ACCESSKEYID
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: "${APP_NAME}-objectstorage-secret"
                - name: FILES_OBJECTSTORAGE_SECRETACCESSKEY
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: "${APP_NAME}-objectstorage-secret"
                - name: APITOKEN
                  valueFrom:
                    secretKeyRef:
                      key: mailapitoken
                      name: "${APP_NAME}-secret"
                - name: WEBHOOK_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: webhooksecret
                      name: "${APP_NAME}-secret"
                - name: EXTERNAL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: externalapikey
                      name: "${APP_NAME}-secret"
                # - name: SERVER_LOGFILE
                #   value: "/var/log/app.log"
              envFrom:
                - configMapRef:
                    name: "medis-rls-frontend-config"
                - configMapRef:
                    name: "medis-rls-sc-config"
                - configMapRef:
                    name: "medis-rls-server-config"
                - configMapRef:
                    name: "medis-rls-service-config"
                - configMapRef:
                    name: "medis-rls-files-config"
                - configMapRef:
                    name: "medis-rls-oidc-config"
                - configMapRef:
                    name: "medis-rls-custombcaddressformiocomponent-config"
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          volumes:
            - name: log-storage
              emptyDir: {}
      test: false
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - app
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: "${APP_NAME}:${JOB_NAME}"
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${APP_NAME}-app-${JOB_NAME}"
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: "${APP_NAME}.${JOB_NAME}"
        role: app
      sessionAffinity: None
parameters:
  - name: APP_NAME
    description: Application name
    displayName: Application name
    required: true
  - name: ROUTE_PATH
    description: Configure the route path (ex. /pr-5 or /app), also used for VITE_FRONTEND_BASEPATH
    displayName: Route path
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: ENVIRONMENT_NAME
    description: Environment name (i.e. 'dev' OR 'prod')
    displayName: Environment Name
    required: true
  - name: IMAGE_REGISTRY
    description: The container registry
    displayName: Image Registry
    required: true
    value: ghcr.io
  - name: IMAGE_NAMESPACE
    description: The image namespace
    displayName: Image Namespace
    required: true
    value: bcgov-tools
  - name: CPU_LIMIT
    description: Limit Peak CPU per pod (in millicores ex. 1000m)
    displayName: CPU Limit
    value: 250m
  - name: CPU_REQUEST
    description: Requested CPU per pod (in millicores ex. 500m)
    displayName: CPU Request
    value: 50m
  - name: MEMORY_LIMIT
    description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
    displayName: Memory Limit
    value: 512Mi
  - name: MEMORY_REQUEST
    description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
    displayName: Memory Request
    value: 256Mi
  - name: REPLICAS
    description: The number of replicas to run
    displayName: Replicas
    value: "2"