# This is a basic workflow that will start a build with every push

name: PCD RLS Deploy on Dev environment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    workflow_dispatch:
      inputs:
        environment:
          description: Environment name; choose dev for PR
          required: true
          type: choice
          options:
          - develop
          default: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
    # Now, oc is available for the rest of these steps.
      - name: Log in to Openshift
        run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER}}
    #check if run return an error

      - name: Tag for Dev
        run: oc start-build pcd-rls -n ${{ secrets.NAMESPACE_SRC }} --follow